### ISSUE TITLE
Submodules

### ISSUE THREAD

**Issue by coot** [input-output-hk/cardano-benchmarking#107]
Using submodules prevents us from using `cardano-repo-tool` with this repository. We either need to remove `cardano-benchmarks` from `cardano-haskell` (which would be unfortunate, as you would not get updates), or stop using submodules in this repository.

**Comment by CodiePP** [comment]
you don't understand how we use git submodules in our setup. They are there to support our development process, but are ignored by CI and other tooling. We have successfully used "cardano-repo-tool" and "cardano-benchmarking" up to now. Due to your misunderstanding the maintainer of cardano-repo-tool has removed our project from the integration. 
https://github.com/input-output-hk/cardano-repo-tool/blob/master/main/cardano-repo-tool.hs#L196

**Comment by coot** [comment]
@CodiePP how do you use `cardano-repo-tool` with `cardano-benchmarks`?

 > Due to your misunderstanding the maintainer of cardano-repo-tool has removed our project from the integration.

If there's a clear way how to use it, let Erik know.
